server:
  port: 8081

#file config
file:
  ip: 116.198.205.248
  port: 8081

# Database Configuration
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root   #Database username
    password: N7r$9vQp!X2bLw8@   #Database password
    url: jdbc:mysql://localhost:3306/manincorp-trading?
      useSSL=false&
      useUnicode=true&characterEncoding=utf-8&
      allowMultiQueries=true&useSSL=false&
      serverTimezone=GMT%2b8&
      allowPublicKeyRetrieval=true
  servlet:
    multipart:
      max-file-size: 100MB     #Maximum size per uploaded file
      max-request-size: 100MB  #Maximum size for a single request

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.manincorp.trading.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #Enable SQL logging
    map-underscore-to-camel-case: true